"""create orders table

Revision ID: 440b068d8ef1
Revises:
Create Date: 2026-09-29 13:24:11.669077

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "440b068d8ef1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
