[project]
name = "mod11_concurrencia_rendimiento"
version = "0.1.0"
description = ""
authors = [
    {name = "karlacr",email = "karlacruzramirez2401@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "httpx (>=0.28.1,<0.29.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "isort (>=9.0.1,<10.0.0)",
    "ruff (>=0.16.7,<0.17.0)",
    "pre-commit (>=4.6.2,<5.0.0)"
]


[tool.poetry]
packages = [
    { include = "mod11_concurrencia_rendimiento", from = "src" }
]

[tool.isort]
profile = "black"
line_length = 88